# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptributo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['pessoa_nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterField(
            model_name='tributos',
            name='is_pago',
            field=models.BooleanField(default=False, verbose_name='Pago?'),
        ),
        migrations.AlterField(
            model_name='tributos',
            name='taxas_impostos',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='veiculo_preco_fipe',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
